site_name: PVTpy
theme:
  name: material
  palette:
    scheme: preference
    primary: blue grey
    accent: deep purple
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Tutorial: 
    - PVT Tables: examples/1-pvt/1a-PVT_Tables.ipynb
    - Chromatography: examples/2-chromatography/1b-Chromatography.ipynb
    #- Fluids:
    #  - Oil:
    #  - Gas:
    #  - Water:

repo_url: https://github.com/scuervo91/pvtpy
repo_name: scuervo91/pvtpy

plugins:
  - search
  - mkdocs-jupyter

markdown_extensions:
  - admonition
